image: node:8-stretch

before_script:
  - apt-get update -qq && apt-get install -y -qq xz-utils lftp

stages:
  - test
  - deploy

test:
  stage: test
  artifacts:
    expire_in: 1 day
    paths:
      - db
  script:
    - mkdir -p db    
    - wget -c https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz    
    - tar xf ffmpeg-release-64bit-static.tar.xz
    - mv ffmpeg-3* ffmpeg
    - git clone https://lab.shelter.moe/karaokemugen/karaokemugen-app.git
    - cd karaokemugen-app
    - npm install
    - touch mpv
    - echo "PathKaras=../karas" >config.ini
    - echo "PathSubs=../lyrics" >>config.ini
    - echo "PathVideos=/shelter/app/data/videos" >>config.ini 
    - echo "BinffmpegLinux=../ffmpeg/ffmpeg" >>config.ini
    - echo "BinffprobeLinux=../ffmpeg/ffprobe" >>config.ini
    - echo "BinPlayerLinux=mpv" >>config.ini
    - echo "PathDB=../db" >>config.ini
    - echo "PathAltname=../series_altnames.csv" >>config.ini
    - npm start -- --debug --generate        
  only:
    - master


shelter:
  stage: deploy
  dependencies:
    - test
  script:
    - cp -f db/karas.sqlite3 /shelter/app/db/karas.sqlite3
    - cd /shelter/app/data/
    - git pull
  only:
    - master

export_website:
  stage: deploy
  dependencies: 
    - test
  script:
    - bash tools/export_json.sh karas karas.json
    - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; cd downloads; put karas.json"
    - rm -f karas.json
    - "curl -X POST -F token=$TRIGGERWEB -F ref=master https://lab.shelter.moe/api/v4/projects/28/trigger/pipeline"
