image: axelterizaki/karaokemugen-ci:node-10

stages:
  - test
  - deploy

test:
  stage: test
  services:
    - postgres:10.6
  variables:
    POSTGRES_USER: karaokemugen_app
    POSTGRES_PASSWORD: musubi
  artifacts:
    expire_in: 1 day
    paths:
      - names.php
  script:
    - apt-get -y install php-pgsql
    - git clone https://lab.shelter.moe/karaokemugen/karaokemugen-app.git
    - cd karaokemugen-app
    - git checkout 379-postgresql
    - yarn install
    - touch mpv
    - cp -f database.CICD.json database.json
    - node util/extUnaccent.js
    - echo "PathKaras=../karas" >config.ini
    - echo "PathSubs=../lyrics" >>config.ini
    - echo "PathSeries=../series" >>config.ini
    - echo "PathMedias=/shelter/app/data/videos" >>config.ini
    - echo "BinPlayerLinux=mpv" >>config.ini
    - yarn start --debug --generate --strict
    - php -f tools/export_karaokesmoe.php >names.php
  only:
    - master
    - postgres


export:
  stage: deploy
  script:
    - lftp -c "set ftp:ssl-allow no; set ftp:charset "UTF-8" ; set file:charset utf-8; open -u $USERNAME,$PASSWORD $HOST; cd live; put names.php ; lcd lyrics ; cd subtitles ; mirror -Rnev --parallel=10"
    - lftp -c "set ftp:ssl-allow no; set ftp:charset "UTF-8" ; set file:charset utf-8; open -u $USERNAME,$PASSWORD $HOST; cd kmserver/app/data/karas ; lcd karas ; mirror -Rnev --parallel=10 ; cd ../lyrics ; lcd ../lyrics ; mirror -Rnev --parallel=10 ; cd ../series  ; lcd ../series ; mirror -Rnev --parallel=10"
    - echo "Triggering KM Server generation"
    - "curl -X POST -H authorization:$KMSERVERAUTH http://kara.moe/api/generate"
  only:
    - master
