image: axelterizaki/karaokemugen-ci

stages:
  - test
  - deploy

cache:
  key: base
  paths:
  - node_modules/
  - react_client/node_modules/

test:
  stage: test
  artifacts:
    expire_in: 1 hour
    paths:
      - db
  script:
    - mkdir -p db
    - git clone https://lab.shelter.moe/karaokemugen/karaokemugen-app.git
    - git checkout next
    - cd karaokemugen-app
    - yarn install
    - touch mpv
    - echo "PathKaras=../karas" >config.ini
    - echo "PathSubs=../lyrics" >>config.ini
    - echo "PathMedias=/shelter/app/data/videos" >>config.ini
    - echo "BinPlayerLinux=mpv" >>config.ini
    - echo "PathDB=../db" >>config.ini
    - echo "PathAltname=../series.json" >>config.ini
    - npm start -- --debug --generate --strict
  only:
    - master


export:
  stage: deploy
  script:
    - php -f tools/export_karaokesmoe.php db/karas.sqlite3 >names.php
    - lftp -c "set ftp:ssl-allow no; set ftp:charset "UTF-8" ; set file:charset utf-8; open -u $USERNAME,$PASSWORD $HOST; cd live; put names.php ; lcd lyrics ; cd subtitles ; mirror -Rnev --parallel=10"
    - bash tools/export_karas.sh db/karas.sqlite3 >karas.json
    - bash tools/export_series.sh db/karas.sqlite3 >series_karas.json
    - bash tools/stats.sh db/karas.sqlite3 >stats.json
    - bash tools/export_tags.sh db/karas.sqlite3 >tags_karas.json
    - bash tools/export_years.sh db/karas.sqlite3 >years_karas.json
    - lftp -c "set ftp:ssl-allow no; set ftp:charset "UTF-8" ; set file:charset utf-8;  open -u $USERNAME,$PASSWORD $HOST; cd site/downloads; put karas.json; put tags_karas.json ; put years_karas.json ; put series_karas.json; put stats.json ; lcd lyrics ; cd .. ; cd lyricsfiles ; mirror -Rnev --parallel=10 ; cd .. ; cd karafiles ; lcd .. ; lcd karas ; mirror -Rnev --parallel=10"
    - "curl -X POST -F token=$TRIGGERWEB -F ref=master https://lab.shelter.moe/api/v4/projects/28/trigger/pipeline"
  only:
    - master
