image: node:8-stretch  

stages:
  - test
  - deploy

test:
  stage: test
  artifacts:
    expire_in: 1 day
    paths:
      - db
  script:
    - mkdir -p db
    - apt-get update -qq && apt-get install -y -qq xz-utils 
    - wget -c https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz    
    - tar xf ffmpeg-release-64bit-static.tar.xz
    - mv ffmpeg-4* ffmpeg
    - git clone https://lab.shelter.moe/karaokemugen/karaokemugen-app.git
    - cd karaokemugen-app
    - git checkout next    
    - npm install
    - touch mpv
    - echo "PathKaras=../karas" >config.ini
    - echo "PathSubs=../lyrics" >>config.ini
    - echo "PathMedias=/shelter/app/data/videos" >>config.ini 
    - echo "BinffmpegLinux=../ffmpeg/ffmpeg" >>config.ini
    - echo "BinffprobeLinux=../ffmpeg/ffprobe" >>config.ini
    - echo "BinPlayerLinux=mpv" >>config.ini
    - echo "PathDB=../db" >>config.ini
    - echo "PathAltname=../series_altnames.csv" >>config.ini
    - npm start -- --debug --generate --strict      
  only:
    - master
  
export_website:  
  stage: deploy
  script:
    - apt-get update -qq && apt-get install -y -qq lftp sqlite3
    - bash tools/export_json.sh db/karas.sqlite3 >karas.json
    - bash tools/stats.sh db/karas.sqlite3 >stats.json
    - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; cd downloads; put karas.json; put stats.json"
    - rm -f *.json
    - "curl -X POST -F token=$TRIGGERWEB -F ref=master https://lab.shelter.moe/api/v4/projects/28/trigger/pipeline"
  only:
    - master
