stages:
  - sync_medias
  - test
  - deploy

sync_medias:
  stage: sync_medias
  image: instrumentisto/rsync-ssh
  interruptible: false
  tags:
    - moeBaseMedias
  retry:
    max: 2
    when:
      - job_execution_timeout
  script:
    - mkdir ~/.ssh
    - echo "$SSH_KEY" > ~/.ssh/id_rsa
    - HOSTKEYS=`ssh-keyscan -H $HOST`
    - echo "$HOSTKEYS" > ~/.ssh/known_hosts
    - chmod -R 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh -l root $HOST
  only:
    refs:
      - master
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /nomedia/

test:
  stage: test
  interruptible: true
  tags:
    - moeBaseMedias
  image: axelterizaki/karaokemugen-ci:node-12-phppg
  services:
    - postgres:10.6
  variables:
    POSTGRES_USER: karaokemugen_app
    POSTGRES_PASSWORD: musubi
  artifacts:
    expire_in: 1 day
    name: names.php
    paths:
      - names.php
      - searchbase.php
  script:
    - apt-get update && apt-get install -y php-intl # To be removed when docker image will come with php-intl
    - git clone https://lab.shelter.moe/karaokemugen/karaokemugen-app.git
    - cd karaokemugen-app
    - git checkout next
    - yarn pull
    - yarn install
    - touch mpv
    - mkdir app
    - cp -f ../tools/config.CICD.yml app/config.yml
    - yarn ts-node util/extUnaccent
    - node -v
    - yarn startNoElectron --debug --generate --strict
    - cd ..
    - php -f tools/export_karaokesmoe.php
  only:
    - master

export:
  stage: deploy
  image: axelterizaki/karaokemugen-ci:transferts
  interruptible: true
  script:
    - lftp -c "set cmd:fail-exit yes; set ftp:ssl-allow no; set ftp:charset "UTF-8" ; set file:charset utf-8; open -u $USERNAME,$PASSWORD $HOST; cd live; put names.php; put searchbase.php ; lcd lyrics ; cd subtitles ; mirror -Rnev --parallel=10"
    - lftp -c "set cmd:fail-exit yes; set ftp:ssl-allow no; set ftp:charset "UTF-8" ; set file:charset utf-8; open -u $USERNAME,$PASSWORD $HOST; cd data-moe/lyrics ; lcd lyrics ; mirror -Rnev --parallel=10 ; cd ../karaokes ; lcd ../karaokes ; mirror -Rnev --parallel=10 ; cd ../tags ; lcd ../tags ; mirror -Rnev --parallel=10"
    - echo "Triggering KM Server generation"
    - "curl -f -X POST -H authorization:$KMSERVERAUTH https://kara.moe/api/generate"
    - "curl -f -X POST -H authorization:$KMSERVERDEVAUTH https://dev.kara.moe/api/generate"
  only:
    - master
