image: node:8-stretch

cache:
  paths:
  - karaokemugen-app/node_modules/
  
stages:
  - install
  - test
  - deploy

installKM:
  stage: install
  artifacts:
    expire_in: 1 day
    paths:
      - karaokemugen-app  
  script:
    - echo test
    - git clone https://lab.shelter.moe/karaokemugen/karaokemugen-app.git
    - cd karaokemugen-app
    - npm install -g yarn
    - yarn install
    - echo "PathKaras=../karas" >config.ini
    - echo "PathLyrics=../lyrics" >>config.ini
    - echo "PathVideos=/shelter/data/videos" >>config.ini    
  only:
    - 399-revoir-l-organisation-et-la-mise-a-jour-du-depot

generateDB:
  stage: test
  dependencies:
    - installKM
  artifacts:
    name: "$CI_COMMIT_REF_NAME-db"
    expire_in: 1 day
    paths:
      - karaokemugen-app/app/db  
  script:
    - apt-get update -qq && apt-get install -y -qq ffmpeg mpv
    - cd karaokemugen-app
    - npm start -- --debug --generate        
  only:
    - 399-revoir-l-organisation-et-la-mise-a-jour-du-depot

shelter:
  stage: deploy
  artifacts:
    name: "$CI_COMMIT_REF_NAME-db"
    expire_in: 1 day
    paths:
      - app/db
  script:
    - cp -f karaokemugen-app/app/db/karas.sqlite3 /shelter/db/karas.sqlite3
    - cd /shelter/data/
    - git pull
  only:
    - 399-revoir-l-organisation-et-la-mise-a-jour-du-depot