image: axelterizaki/karaokemugen-ci:node-10-pg

stages:
  - sync_medias
  - test
  - deploy

sync_medias:
  stage: sync_medias
  interruptible: false
  script:
    - mkdir ~/.ssh
    - echo "$SSH_KEY" > ~/.ssh/id_rsa
    - HOSTKEYS=`ssh-keyscan -H $HOST`
    - echo "$HOSTKEYS" > ~/.ssh/known_hosts
    - chmod -R 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh -l root $HOST
  only:
    - master

test:
  stage: test
  interruptible: true
  services:
    - postgres:10.6
  variables:
    POSTGRES_USER: karaokemugen_app
    POSTGRES_PASSWORD: musubi
  artifacts:
    expire_in: 1 day
    name: names.php
    paths:
      - names.php
  script:
    - git clone https://lab.shelter.moe/karaokemugen/karaokemugen-app.git
    - cd karaokemugen-app
    - yarn pull
    - yarn install
    - touch mpv
    - cp -f database.CICD.json database.json
    - cp -f ../tools/config.CICD.yml config.yml
    - node util/extUnaccent.js
    - node -v
    - yarn start --debug --generate --strict
    - cd ..
    - php -f tools/export_karaokesmoe.php >names.php
  only:
    - master

export:
  stage: deploy
  interruptible: true
  script:
    - lftp -c "set cmd:fail-exit yes; set ftp:ssl-allow no; set ftp:charset "UTF-8" ; set file:charset utf-8; open -u $USERNAME,$PASSWORD $HOST; cd live; put names.php ; lcd lyrics ; cd subtitles ; mirror -Rnev --parallel=10"
    - lftp -c "set cmd:fail-exit yes; set ftp:ssl-allow no; set ftp:charset "UTF-8" ; set file:charset utf-8; open -u $USERNAME,$PASSWORD $HOST; cd kmserver/app/data/karas ; lcd karas ; mirror -Rnev --parallel=10 ; cd ../lyrics ; lcd ../lyrics ; mirror -Rnev --parallel=10 ; cd ../series ; lcd ../series ; mirror -Rnev --parallel=10 ; cd ../karaokes ; lcd ../karaokes ; mirror -Rnev --parallel=10 ; cd ../tags ; lcd ../tags ; mirror -Rnev --parallel=10"
    - echo "Triggering KM Server generation"
    - "curl -X POST -H authorization:$KMSERVERAUTH http://kara.moe/api/generate"
    - "curl -X POST -H authorization:$KMSERVERDEVAUTH http://dev.kara.moe/api/generate"
  only:
    - master
