System:
  Binaries:
    Player:
      Linux: mpv
  Repositories:
    - Name: kara.moe
      Online: false
      Enabled: true
      Path:
        Karas:
          - ../../karaokes
        Lyrics:
          - ../../lyrics
        Series:
          - ../../series
        Medias:
          - /medias
        Tags:
          - ../../tags
