System:
  Binaries:
    Player:
      Linux: mpv
  Path:
    Karas:
      - ../../karaokes
    Lyrics:
      - ../../lyrics
    Series:
      - ../../series
    Medias:
      - /medias
    Tags:
      - ../../tags
